### ISSUE TITLE
How do we ignore certain files so DNT does not try to output them

### ISSUE THREAD

**Issue by mcasaresmdevz** [denoland/dnt#285] opened 2023-05-15 14:42 UTC
When using DNT it currently includes all files in the output, regardless of whether they are intended to be part of the package or not. This creates a problem when there are certain files that should be ignored during the build process. We need a mechanism to specify which files should be excluded from the output.

## Expected Behavior
DNT should provide a way to define a set of files that should be ignored during the build process, ensuring that they are not included in the final output package.

## Current Behavior
Currently, DNT includes all files present in the project directory when building the package, even if they are not meant to be part of the package. This can lead to unnecessary files being included in the output.

## Steps to Reproduce
Install and set up DNT in a project.
Run the build command (dnt build) with files that should be ignored present in the project directory.
Notice that the output package includes all files, including the ones that should have been ignored.

## Proposed Solution
It would be beneficial to introduce a configuration option or a file-based mechanism, such as a .dntignore file, that allows developers to specify files or directories that should be ignored during the build process. This way, DNT can exclude those files when generating the output package.

**Comment by dsherret** [comment] 2023-05-17 21:02
> Currently, DNT includes all files present in the project directory when building the package, even if they are not meant to be part of the package. This can lead to unnecessary files being included in the output.

Could you provide an example? It should only include files in the directory that are found based on the provided entrypoints and their module graph (ex. `entrypoints: ["./mod.ts"]`). It shouldn't be including other files.

You can use a postbuild step to delete any files you don't want, but then that likely will stop your package from running correctly since some of the entrypoints' dependent files would be missing:

await build({
  // ...etc...
  outDir: "./npm",
  postBuild() {
    Deno.removeSync("npm/...file_to_delete_goes_here...");
  },
});

**Comment by dsherret** [comment] 2023-06-02 14:24
Going to close this one because I don't think it's actionable. Another source of files it may pull in is test files. See this section of the docs on how you can change the test pattern: https://github.com/denoland/dnt#test-file-matching

```ts
await build({
  // ...etc...
  testPattern: "**/*.test.{ts,tsx,js,mjs,jsx}",
  // and/or provide a directory to start searching for test
  // files from, which defaults to the current working directory
  rootTestDir: "./tests",
});
```

**Closed by dsherret** 2023-06-02 14:24 UTC

**Comment by talentlessguy** [comment] 2023-11-24 00:56
I have the same problem - test files and shims end up in the package. They shouldn't be there

**Comment by dsherret** [comment] 2023-11-24 00:58
@talentlessguy it's a bug that they end up in the package--it's not something you should have to configure. Can you open an issue that has a reproduction?

**Comment by talentlessguy** [comment] 2023-11-24 01:37
@dsherret opened https://github.com/denoland/dnt/issues/353

**Comment by dsherret** [comment] 2023-11-24 01:54
@talentlessguy thanks! I will look tomorrow morning
