### ISSUE TITLE
Improve dnt mappings version handling.

### ISSUE THREAD

**Issue by UrielCh** [denoland/dnt#308] opened 2023-05-27 09:44 UTC
Hi,

Is there a wait to widecard package version in dnt mapping ?

I update one of my project dependencies from:
`https://deno.land/x/logger@v1.1.0/logger.ts`
to
`https://deno.land/x/logger@v1.1.1/logger.ts`

but once My automation deployment stript ran they failed, because, my DNT configuration contains:
```js
      "https://deno.land/x/logger@v1.1.0/logger.ts": {
        name: "@denodnt/logger",
        version: "1.1.0",
        peerDependency: false,
      },
```
instead of
```js
      "https://deno.land/x/logger@v1.1.1/logger.ts": {
        name: "@denodnt/logger",
        version: "1.1.1",
        peerDependency: false,
      },
```

Is it possible to write something like:

```js
      "https://deno.land/x/logger@v{VERSION}/logger.ts": {
        name: "@denodnt/logger",
        version: "{VERSION}",
        peerDependency: false,
      },
```

So I do not need to update my don't each time I update my dependencies version.

**Comment by UrielCh** [comment] 2023-05-28 05:03
My first idea was to use a RegExp.

```ts
  "https://deno.land/x/logger@v$([\d-]+)/logger.ts": {
        name: "@denodnt/logger",
        version: "$1",
        isRegexp: true,
        peerDependency: false,
      },
```

**Comment by dsherret** [comment] 2023-06-08 16:51
This is actually a duplicate of #151

**Closed by dsherret** 2023-06-08 16:51 UTC
Labels: duplicate, enhancement
